#!/bin/bash
set -e

symbols_file="${UNIPICKER_SYMBOLS_FILE}"
select_command=${UNIPICKER_SELECT_COMMAND:-fzf}

usage () {
  echo "Select unicode character by description"
  echo ""
  echo "Usage: unipicker [--command cmd] [--copy-command cmd ] [--copy] [--list]"
  echo ""
  echo "Arguments:"
  echo "  --command       Overrides default select command"
  echo "  --list          Only list the symbols, do not select or copy"
  echo "  --symbols       Location of symbols file"
  echo ""
  echo "Variables:"
  echo ""
  echo "  UNIPICKER_SELECT_COMMAND  Command to use for selecting (= $select_command)"
  echo "  UNIPICKER_SYMBOLS_FILE    Location of symbols (/usr/share/unipicker/symbols or ~/.local/share/unipicker/symbols or ${PWD}/symbols)"
}

while [ -n "$1" ];do
    case "$1" in
        --command)
            select_command=$2
            shift
            ;;
        --symbols)
            symbols_file=$2
            shift
            ;;
        --list)
            cat "$symbols_file"
            exit;;
        -h|--help)
            usage
            exit;;
        *)
            echo "Invalid argument: $1"
            exit 1;;
    esac
    shift
done

if [ -f $symbols_file ] ; then
    if [ -f /usr/share/unipicker/symbols ]; then
        symbols_file=/usr/share/unipicker/symbols
    elif [ -f ~/.local/share/unipicker/symbols ]; then
        symbols_file=~/.local/share/unipicker/symbols
    elif [ -f ${PSW}/symbols ]; then
        symbols_file=${PSW}/symbols
    else
        echo not found symbols file $symbols_file > /dev/stderr;
        exit 1
    fi
fi
cat "$symbols_file" | $select_command | sed -E 's/^(.).*/\1/g'
