---
name: Test

on:
  push:

jobs:
  test-generated-symbols-match-with-blocks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: generate symbols
      run: make clean symbols
    - name: symbols stored in repository should be updated
      run: test -z $(git ls-files --modified)

