---
name: Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: generate symbols
      run: make clean symbols
    - name: symbols stored in repository should be updated
      run: test -z $(git ls-files --modified)
    - name: Reverse generate Blocks.patch
      run: diff -du Blocks.txt BlocksReduced.txt > Blocks.patch
    - name: test uniform format for patch (gnu diff)
      run: test -z $(git ls-files --modified)

